name: Build and Deploy

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Cache apt packages
        uses: actions/cache@v3
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-apt-texlive-${{ hashFiles('**/ci.yml') }}
          restore-keys: |
            ${{ runner.os }}-apt-texlive-
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --download-only texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra
          sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra
      
      - name: Build PDFs
        run: make all
